from django.urls import path
from . import views


urlpatterns = [
    # path('',views.main_view,name='main_view'),
    path('',views.login,name="login"),
    path('test/<str:a>/<str:b>/', views.test, name='test'),
    path("login/",views.login,name="login"),
    path("authenticate/",views.authenticate,name="authenticate"),
    path("product_new/<int:c_page>/<int:t_pages>/",views.product_new,name="product_new"),
    path("product_add/<int:c_page>/<int:t_pages>/",views.product_add,name='"product_add'),
    path('prod_search/<int:c_page>/<int:t_pages>/',views.prod_search,name="prod_search"),
    path('product_update/<int:c_page>/<int:t_pages>/',views.product_update,name='product_update'),
    path('product_delete/<int:c_page>/<int:t_pages>/',views.product_delete,name="product_delete"),
    path('customer_new/<int:c_page>/<int:t_pages>/',views.customer_new,name="customer_new"),
    path('customer_add/<int:c_page>/<int:t_pages>/',views.customer_add,name="customer_add"),
    path('customer_update/<int:c_page>/<int:t_pages>/',views.customer_update,name='cusotmer_update'),
    path('customer_delete/<int:c_page>/<int:t_pages>/',views.customer_delete,name='cusotmer_delete'),
    path('customer_search/<int:c_page>/<int:t_pages>/',views.customer_search,name='customer_search'),
    path('partner_new/<int:c_page>/<int:t_pages>/',views.partner_new,name='partner_new'),
    path('partner_add/<int:c_page>/<int:t_pages>/',views.partner_add,name='partner_add'),
    path('partner_delete/<int:c_page>/<int:t_pages>/',views.partner_delete,name='partner_delete'),
    path('partner_update/<int:c_page>/<int:t_pages>/',views.partner_update,name='partner_update'),
    path('partner_search/<int:c_page>/<int:t_pages>/',views.partner_search,name='partners_search'),
    path('rfp_new/<int:c_page>/<int:t_pages>/',views.rfp_new,name='rfp_new'),
    path('rfp_add/<int:c_page>/<int:t_pages>/',views.rfp_add,name='rfp_add'),
    path('rfp_delete/<int:c_page>/<int:t_pages>/',views.rfp_delete,name='rfp_delete'),
    path('rfp_update/<int:c_page>/<int:t_pages>/',views.rfp_update,name='rfp_update'),
    path('rfp_search/<int:c_page>/<int:t_pages>/',views.rfp_search,name='rfp_search'),
    path("qa_new/<int:c_page>/<int:t_pages>/",views.qa_new,name='qa_new'),
    path('qa_add/<int:c_page>/<int:t_pages>/',views.qa_add,name='qa_add'),
    path('qa_update/<int:c_page>/<int:t_pages>/',views.qa_update,name='qa_update'),
    path('qa_delete/<int:c_page>/<int:t_pages>/',views.qa_delete, name ='qa_delete'),
    path('qa_search/<int:c_page>/<int:t_pages>/',views.qa_search, name ='qa_search'),
    path('product_type_lookup/<str:p_type>/',views.product_type_lookup,name="product_type_lookup"),
    path('product_type_add/',views.product_type_add,name='prod_type_add'),
    path('product_type_del/',views.product_type_del,name="product_type_del"),
    path('product_type_update/',views.product_type_update,name="product_type_update"),
    path('customer_type_lookup/<str:c_type>/',views.customer_type_lookup,name="customer_type_lookup"),
    path('customer_type_add/',views.customer_type_add,name='customer_type_add'),
    path('customer_type_del/',views.customer_type_del,name="customer_type_del"),
    path('customer_type_update/',views.customer_type_update,name='customer_type_update'),
    path('partner_lookup/<str:p_type>/',views.partner_lookup,name="partner_lookup"),
    path('partner_lu_add/',views.partner_lu_add,name="partner_lu_add"),
    path('partner_lu_del/',views.partner_lu_del,name='partner_lu_del'),
    path('partner_lu_update/',views.partner_lu_update,name='partner_lu_update'),
    path('tender_lookup/<str:t>/',views.tender_lookup,name =" tender_lookup"),
    path('product_lookup/<str:p>/',views.product_lookup,name =" product_lookup"),
    path('user_new/<int:c_page>/<int:t_pages>/',views.user_new,name="user_new"),
    path('user_search/',views.user_search,name='user_search'),
    path('user_delete/',views.user_delete,name='user_delete'),
    path('user_add/',views.user_add,name="user_add"),
    path("user_update/",views.user_update,name="user_update"),
]